/**
 * generate-seed.mjs
 * ────────────────────────────────────────────────────────────────────────────
 * Reads data/moussy_legend_keys.csv (the EXACT file uploaded to Fungies — the
 * single source of truth) and emits migrations/0002_seed_legend_keys.sql with
 * one `INSERT OR IGNORE` per key, normalized (trimmed, trailing comma stripped,
 * uppercased). Re-running is safe and idempotent.
 *
 *   node scripts/generate-seed.mjs
 *
 * Then apply with:
 *   wrangler d1 migrations apply moussy-license          (remote)
 *   wrangler d1 migrations apply moussy-license --local  (local dev)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const CSV = join(__dirname, '..', 'data', 'moussy_legend_keys.csv');
const OUT = join(__dirname, '..', 'migrations', '0002_seed_legend_keys.sql');

const KEY_RE = /^[A-Z0-9]{5}-[A-Z0-9]{5}-[A-Z0-9]{5}$/;

const raw = readFileSync(CSV, 'utf8');
const keys = [];
const seen = new Set();

for (const line of raw.split(/\r?\n/)) {
  // strip trailing comma + surrounding whitespace, uppercase
  const key = line.replace(/,\s*$/, '').trim().toUpperCase();
  if (!key) continue;                       // blank line
  if (!KEY_RE.test(key)) {
    throw new Error(`Malformed key in CSV: "${line}" -> "${key}"`);
  }
  if (seen.has(key)) continue;              // dedupe
  seen.add(key);
  keys.push(key);
}

const lines = [];
lines.push('-- ════════════════════════════════════════════════════════════════════════');
lines.push('-- 0002 — Seed Legend key inventory  (GENERATED by scripts/generate-seed.mjs)');
lines.push(`-- Source: data/moussy_legend_keys.csv   Keys: ${keys.length}`);
lines.push('-- Do not edit by hand — regenerate from the CSV instead.');
lines.push('-- ════════════════════════════════════════════════════════════════════════');
for (const key of keys) {
  lines.push(`INSERT OR IGNORE INTO legend_keys (key) VALUES ('${key}');`);
}
lines.push('');

writeFileSync(OUT, lines.join('\n'), 'utf8');
console.log(`Wrote ${keys.length} keys -> ${OUT}`);
